### ISSUE TITLE
Simplify error management with thiserror

### ISSUE THREAD

**Issue by fxwiegand** [rust-bio/rust-bio-tools#126]
Pretty much analog to https://github.com/rust-bio/rust-bio/issues/341, `rbt` should also start using [thiserror](https://github.com/dtolnay/thiserror) and [anyhow](https://github.com/dtolnay/anyhow) to simplify error management.

**Comment by natir** [comment]
It's ready for review ?

**Comment by fxwiegand** [comment]
> It's ready for review ?

There are still lots more of potential more detailed error messages from #29 that could actually be converted and used so i still want to go through all of these and see which ones are a _must_ and which ones are not that important. If you have any suggestions on how to improve what I did until now please let me know. I am definitely still figuring out how to use both anyhow and thiserror in the best way possible.
