### ISSUE TITLE
Requires ruamel.yaml

### ISSUE THREAD

**Issue by JeroenMerks** [rust-bio/rust-bio-tools#2]
sudo pip install ruamel.yaml

Thanks for making this tool ;-)

**Comment by johanneskoester** [comment]
I think you are referring to a conda issue. Rust-bio-tools itself is pure rust and has nothing to do with Python. Can you please report the issue at the conda issue tracker?

**Comment by johanneskoester** [comment]
Apart from that, thanks for using rbt!

**Comment by JeroenMerks** [comment]
You're right, it seems to be a known issue in Conda and reported the issue to them.
