### ISSUE TITLE
[vcf-report] 0-based position reporting for 1-based VCF file

### ISSUE THREAD

**Issue by hassanfa** [rust-bio/rust-bio-tools#230]
In my VCF file, I have a variant at the following specific position:

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TUMOR
22	42524491	.	C	<DUP>	334	PASS	TYPE=DUP;AF=0.1005; GT:DP 0/1:3091
```

Above variant is missing HGVSg and `vcf-report` clearly reports it. But it reports a 0-based position. It is a minor issue, but it'd be useful to either properly have it 1-based or clearly specify what convention vcf-report is using for reporting. I prefer the former, it just makes the debugging easier.

Also, it does not report chromosome either.

Here is the `vcf-report` output:
```
thread '<unnamed>' panicked at 'Failed building table report for sample a. Found variant . at position 42524490 with no HGVSg value.', src/main.rs:207:21
```

Ideally the output could be something like:
```
thread '<unnamed>' panicked at 'Failed building table report for sample a. Found variant . at position 22:42524491 with no HGVSg value.', src/main.rs:207:21
```

**Comment by hassanfa** [comment]
Looking in the code, it seems `pos` is assigned but `chrom` is not:
https://github.com/rust-bio/rust-bio-tools/blob/d1a60cc8876eb8ea2b6cffb21bdcee44a00d2dc4/src/bcf/report/table_report/create_report_table.rs#L85-L110

I'll look into the contribution guide and give this is a go.

**Comment by hassanfa** [comment]
@fxwiegand thanks for the quick fix. Yes, you are absolutely right that I was not using the latest version.

**Comment by fxwiegand** [comment]
> @fxwiegand thanks for the quick fix. Yes, you are absolutely right that I was not using the latest version.

Ok great! Thank you though for pointing out the wrongly payed position! 😊
