### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by andrewrech** [rust-bio/rust-bio-tools#4]
From repo

`cargo 0.20.0-nightly (397359840 2017-05-18)`
`nightly-x86_64-apple-darwin - rustc 1.19.0-nightly (81734e0e0 2017-05-22)`

> Installing rust-bio-tools v0.1.2 (file:///Users/USER/rust-bio-tools)
>    Compiling bit-vec v0.4.3
>    Compiling log v0.3.7
>    Compiling approx v0.1.1
>    Compiling bitflags v0.5.0
>    Compiling strsim v0.4.1
>    Compiling itertools v0.4.19
>    Compiling custom_derive v0.1.7
>    Compiling libc v0.2.23
>    Compiling num-traits v0.1.37
>    Compiling void v1.0.2
> warning[E0122]: trait bounds are not (yet) enforced in type definitions
>    --> /Users/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.4.19/src/lib.rs:123:1
>     |
> 123 | pub type MapFn<I, B> where I: Iterator = iter::Map<I, fn(I::Item) -> B>;
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    Compiling semver v0.1.20
>    Compiling lazy_static v0.1.16
>    Compiling rust-htslib v0.9.0
>    Compiling ieee754 v0.1.1
>    Compiling fern v0.3.5
> Compiling rustc-serialize v0.3.24
> error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
>    --> /Users/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/ieee754-0.1.1/src/lib.rs:164:17
>     |
> 164 |                 Self::from_bits(bits)
>     |                 ^^^^^^^^^^^^^^^
> ...
> 290 | mk_impl!(f32, u32, u8, u32, 8, 23);
>     | ----------------------------------- in this macro invocation
>     |
>     = help: add #![feature(float_bits_conv)] to the crate attributes to enable
> error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
>    --> /Users/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/ieee754-0.1.1/src/lib.rs:164:17
>     |
> 164 |                 Self::from_bits(bits)
>     |                 ^^^^^^^^^^^^^^^
> ...
> 291 | mk_impl!(f64, u64, u16, u64, 11, 52);
>     | ------------------------------------- in this macro invocation
>     |
>     = help: add #![feature(float_bits_conv)] to the crate attributes to enable
> error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
>    --> /Users/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/ieee754-0.1.1/src/lib.rs:178:17
>     |
> 178 |                 Self::from_bits(bits)
>     |                 ^^^^^^^^^^^^^^^
> ...
> 290 | mk_impl!(f32, u32, u8, u32, 8, 23);
>     | ----------------------------------- in this macro invocation
>     |
>     = help: add #![feature(float_bits_conv)] to the crate attributes to enable
> error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
>    --> /Users/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/ieee754-0.1.1/src/lib.rs:178:17
>     |
> 178 |                 Self::from_bits(bits)
>     |                 ^^^^^^^^^^^^^^^
> ...
> 291 | mk_impl!(f64, u64, u16, u64, 11, 52);
>     | ------------------------------------- in this macro invocation
>     |
>     = help: add #![feature(float_bits_conv)] to the crate attributes to enable
> error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
>    --> /Users/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/ieee754-0.1.1/src/lib.rs:205:17
>     |
> 205 |                 Self::from_bits(
>     |                 ^^^^^^^^^^^^^^^
> ...
> 290 | mk_impl!(f32, u32, u8, u32, 8, 23);
>     | ----------------------------------- in this macro invocation
>     |
>     = help: add #![feature(float_bits_conv)] to the crate attributes to enable
> error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
>    --> /Users/USER/.cargo/registry/src/github.com-1ecc6299db9ec823/ieee754-0.1.1/src/lib.rs:205:17
>     |
> 205 |                 Self::from_bits(
>     |                 ^^^^^^^^^^^^^^^
> ...
> 291 | mk_impl!(f64, u64, u16, u64, 11, 52);
>     | ------------------------------------- in this macro invocation
>     |
>     = help: add #![feature(float_bits_conv)] to the crate attributes to enable
> error: aborting due to 6 previous errors
> error: Could not compile `ieee754`.
> Build failed, waiting for other jobs to finish...

**Thanks!**

**Comment by johanneskoester** [comment]
Thanks! However, this is a failure in nightly, also related to a dependency. We only aim at building on stable rust. Often, failures in nightly are temporal bugs.

**Comment by andrewrech** [comment]
Hello Johannes,

Thanks for the note, sorry about that. I was able to build with stable.

Andrew

**Comment by johanneskoester** [comment]
No problem, thanks for using rbt! Note that you can also install it via bioconda in case you only want to use it.
