### ISSUE TITLE
Broken CI build

### ISSUE THREAD

**Issue by carrascomj** [rust-bio/rust-bio-tools#43]
Hello! 

Last merge broke the CI pipeline. I am getting the [same errors as in travis](https://travis-ci.org/rust-bio/rust-bio-tools/builds/655360350?utm_source=github_status&utm_medium=notification) when I locally run `cargo build`. 

I wanted to try to implement some stuff here, do I have to install to dependencies that are not listed? Or was the `Cargo.toml` file improperly pushed?

**Comment by dlaehnemann** [comment]
Hi @carrascomj, we're looking into it. Locally, it builds for @FelixMoelder. One idea is that it's something to do with a certain cargo/rust version. So we're rerunning the CI to see if it works with a newer cargo version...

**Comment by dlaehnemann** [comment]
Still failing, so @FelixMoelder will try with updating to the current `rust-htslib`, because that is what is currently failing the builds on Travis and it makes sense to update that dependency, anyways.

**Comment by carrascomj** [comment]
Nice, thanks for the quick response!

**Comment by FelixMoelder** [comment]
Hi @carrascomj, we've updated rust-bio-tools to rust-htslib 0.26. TravisCI seems to work again and the [PR](https://github.com/rust-bio/rust-bio-tools/pull/44) should be merged into the master branach asap.

**Comment by carrascomj** [comment]
Alright! All the checks have passed finally :).
